server:
  port: 9092
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/said
    username: postgres
    password: admin
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
exampleListValue: ${EXAMPLE_VALUE}

logging:
  file:
    name: logs/said-log.log
  level:
    root: INFO

---
spring:
  profiles: h2usage
  datasource: