server:
  port: 9092
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/said
    username: postgres
    password: admin
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
exampleListValue: ${EXAMPLE_VALUE}
data:
  rest:
    base-path: /api

logging:
  file:
    name: logs/said-log.log
  level:
    root: INFO

---
spring:
  profiles: testH2
  datasource:
    driverClassName: org.h2.Driver
    url: url:jdbc:h2:mem:testdb
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

---
spring:
  profiles: webflux
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://localhost:5432/postgres
    username: postgres
    password: admin
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true